/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RRule {
  constructor(freq: Frequency)
  get freq(): Frequency
}

export declare const enum Frequency {
  Yearly = 'Yearly',
  Monthly = 'Monthly',
  Weekly = 'Weekly',
  Daily = 'Daily',
  Hourly = 'Hourly',
  Minutely = 'Minutely',
  Secondly = 'Secondly'
}
